In [15]:
import torch
import numpy as np
import time

In [26]:
size = 3000

In [27]:
print(torch.cuda.device_count())
print(torch.cuda.current_device())
torch.cuda.get_device_properties(0)

2
0


_CudaDeviceProperties(name='GeForce GTX 1080 Ti', major=6, minor=1, total_memory=11169MB, multi_processor_count=28)

In [34]:
print(time.time())
A = np.random.rand(size, size).astype(np.float32)
B = np.random.rand(size, size).astype(np.float32)
C = A.dot(B)
print(time.time())

1541367984.101689
1541367984.4177346


In [39]:
print(time.time())
A = torch.rand(size, size).cuda()
B = torch.rand(size, size).cuda()
C = torch.mm(A, B)
print(time.time())

1541368086.9258344
1541368087.0910802


In [40]:
#create zero matrix
torch.zeros(5, 5, dtype = torch.float32)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [41]:
#create uninitialized matrix
torch.empty(5, 5)

tensor([[1.4641e+21, 4.5556e-41, 1.4641e+21, 4.5556e-41, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [42]:
#construct tensor directly from data
torch.tensor([5, 5])

tensor([5, 5])

In [47]:
#torch tensor to numpy array
a = torch.randn(5, 5)
b = a.numpy()
#numpy array is changed even after this operation:
a.add_(1)
#add_ is in place addition
print(a)
print(b)

tensor([[ 1.7078,  1.3288,  1.2232,  2.7432,  0.6179],
        [ 1.8823,  1.3913,  1.4289,  1.4856,  1.2451],
        [ 0.9528,  1.8660,  1.6291,  0.7027,  0.2968],
        [ 0.8592, -0.1816,  1.7505, -1.0943,  2.3067],
        [ 1.8953,  1.1095,  1.2406,  0.7206,  2.9639]])
[[ 1.7078449   1.3288391   1.2231958   2.7431757   0.61790967]
 [ 1.8823378   1.3913293   1.4289138   1.4856381   1.24515   ]
 [ 0.95280796  1.8660489   1.6290544   0.702707    0.29679626]
 [ 0.8592217  -0.18157816  1.750478   -1.0942705   2.306712  ]
 [ 1.8952966   1.1095088   1.2406056   0.72064996  2.9639225 ]]


In [49]:
#creating tensor from numpy
c = torch.from_numpy(b)
c

tensor([[ 1.7078,  1.3288,  1.2232,  2.7432,  0.6179],
        [ 1.8823,  1.3913,  1.4289,  1.4856,  1.2451],
        [ 0.9528,  1.8660,  1.6291,  0.7027,  0.2968],
        [ 0.8592, -0.1816,  1.7505, -1.0943,  2.3067],
        [ 1.8953,  1.1095,  1.2406,  0.7206,  2.9639]])

In [52]:
#cuda tensors:
#only this code part will be run if cuda is available
if torch.cuda.is_available():
    device = torch.device("cuda")
    #directly create on gpu
    y = torch.ones(5, 5, device = device)
    c = c.to(device)
    d = c+y
    print(d)

tensor([[ 2.7078,  2.3288,  2.2232,  3.7432,  1.6179],
        [ 2.8823,  2.3913,  2.4289,  2.4856,  2.2452],
        [ 1.9528,  2.8660,  2.6291,  1.7027,  1.2968],
        [ 1.8592,  0.8184,  2.7505, -0.0943,  3.3067],
        [ 2.8953,  2.1095,  2.2406,  1.7206,  3.9639]], device='cuda:0')


## as mentioned on site's tutorial: ##
**  It is a define-by-run framework, which means that your backprop is defined by how your code is run, and that every single iteration can be different. **


 - torch.Tensor is the central class of the package. 
 - If you set its attribute .requires_grad as True, it starts to track all operations on it. 
 - When you finish your computation you can call .backward() and have all the gradients computed automatically
 - The gradient for this tensor will be accumulated into .grad attribute
 - use .backward function to get derivative

In [83]:
from torch.autograd import Variable

In [88]:
x = Variable(torch.FloatTensor(5, 5),requires_grad = True)
x = x+5
y = x*x
y = y+2
z = y.mean()
z.backward()
print(z.grad)
#tensors created by users have grad_fn None

None
